name: Tests the examples in README
on: push

env:
  TYPECHECK: True

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install uv
          python -m uv pip install --upgrade pip
          python -m uv pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu
          python -m uv pip install -e .[test]
      - name: Test with pytest
        run: |
          python -m pytest tests/
